### ISSUE TITLE
Allow custom groups

### ISSUE THREAD

**Issue by ysaliens** [saites/music-blitz#28]
App correctly reads groups from LIFX app.

However, allowing custom groups (only for this app) could add usefulness for those users who put all lights in a room under a single group. Since LIFX doesn't support multiple groups, being able to break the lights in a room better might be of value. Low priority.

**Comment by saites** [comment]
You can change the grouping that Music Blitz uses on the Light Discovery screen. If you long-press a light, it'll bring up a prompt to Delete the bulb or Change it's group. The initial group is based on the Lifx Group, and if you never change it, it should update with it. If you do set a custom group name, it'll override that and use it instead. Any bulbs with the same group name are considered to be in the same group.

Does that fit this, or did you have something else in mind?

**Comment by ysaliens** [comment]
Aha, that is EXACTLY what I wanted! So long as the new groups I assign are not saved back into LifX, this is perfect. I'll test it when I get home tonight

**Comment by saites** [comment]
Yes, the groups are set only in Music Blitz's data -- not sent back. 

If you change the group name in Music Blitz, it'll ignore the group name for the bulb from there on out. You can delete the bulb and perform discover again though to get it back to default.

It would be cool to have a different UI for it so the groups where more obvious. The bulbs are sorted by group (then alphabetically), but instead of showing them in a list, maybe I could show groups as a sort of box containing bulbs. Then you could drag bulbs from one group to another, and I could have a little "+" to add a new group. That would also make it easier to turn on/off entire groups at once.

**Comment by ysaliens** [comment]
Certainly a UI improvement yeah. Not critical by any means. I'm closing this issue then, it works like I want.
PS....maybe add that in some help/setting/box that it does that.
