### ISSUE TITLE
Unable to link Spotify account to music-blitz?

### ISSUE THREAD

**Issue by NNickey** [saites/music-blitz#34]
I force closed both Spotify and Blitz, made sure its 'broadcasting' in the Spotify app, cleared cache.

I just recently changed my Spotify password and removed the authorization from 'approved applications' on Spotify.com

I can't seem to get the app to bring up the 'Spotify login/authorize' page again?

**Comment by saites** [comment]
I'm sorry for the trouble. Let's see if we can get it resolved.

Just to make sure, you do still have Spotify installed, right? Their sdk requires it in order to login.

Android has two storages for applications, but only one can be cleared if you uninstall, so on thing to try is installing, deleting both sets of data, then reinstalling.

The app itself has an option at the bottom of the settings menu to "log out of Spotify"; this clears the token information the app associates with Spotify (but doesn't/can't disable app access -- that's something you have to do via Spotify's website, as you found). Clearing the data in the above way will also remove this data.

**Comment by NNickey** [comment]
I know about logging out and even tried to remove the applet from the Spotify website, the thing is, I can't get this app to bring up a login page and it always spits this error in notifications. I try to reinstall the app, clear data for both apps, make sure Device broadcast is on, and I even see the Blitz app flash the loading icon and text but it won't let me link to my account because it doesn't bring it up and I removed it from my Spotify authorized apps...
![Screenshot_20191021-145412](https://user-images.githubusercontent.com/3466265/67242638-28592e80-f413-11e9-9886-4f196bf3e263.png)

**Comment by NNickey** [comment]
It's acting like it's authorized to my Spotify account but it's not..

**Comment by saites** [comment]
> I even see the Blitz app flash the loading icon and text 

This is actually it calling out to the Spotify SDK to ask it to log you in. It returns either a token used for further requests, or an error. If it disappears immediately and no error pops up, then the Spotify returned a valid token to the application. From the app's perspective, the token is valid.

In your screenshot, I see it's not able to get tracks. Unfortunately that's a catch-all error message, since the issue could be network, login, missing track info, etc. After some investigation, I think Spotify's APIs might not be responding to my app's requests. They have a dashboard online that shows how many requests are being made with my app's token, and I see a sudden drop to zero starting earlier this month. I don't know why that might be, but I will investigate it further. 

Again, I'm sorry for the issue and I'll see what I can do to get it resolved. The unfortunate part of relying on an external data source is exactly this sort of issue.

**Comment by saites** [comment]
I may have found the issue -- can you try again?

**Comment by NNickey** [comment]
Got it to show the login page, works

**Comment by saites** [comment]
Excellent. I'm sorry for the trouble.
